# Generated by Django 2.1.11 on 2020-03-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_angular', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('H', 'Female')], db_index=True, max_length=1)),
                ('age', models.CharField(max_length=10)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('statusList', models.CharField(choices=[('P', 'Positive'), ('D', 'Dead'), ('R', 'Recovered')], db_index=True, max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
