# Generated by Django 2.1.3 on 2020-03-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_angular', '0002_auto_20200321_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formgroup',
            name='statusList',
        ),
        migrations.AlterField(
            model_name='formgroup',
            name='status',
            field=models.CharField(choices=[('P', 'Positive'), ('D', 'Dead'), ('R', 'Recovered')], db_index=True, max_length=1),
        ),
    ]
