# Generated by Django 2.1.3 on 2020-03-25 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls_angular', '0003_auto_20200324_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='formgroup',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
